package parsers

import "testing"

func TestParseComposerLock(t *testing.T) {
	body := []byte(`{
		"packages": [
			{"name": "monolog/monolog", "version": "2.9.1"},
			{"name": "guzzlehttp/guzzle", "version": "v7.5.0"}
		],
		"packages-dev": [
			{"name": "phpunit/phpunit", "version": "9.6.0"}
		]
	}`)
	deps, err := Parse("composer.lock", body)
	if err != nil {
		t.Fatalf("Parse(composer.lock): %v", err)
	}
	assertContains(t, deps,
		"monolog/monolog@2.9.1/composer",
		"guzzlehttp/guzzle@7.5.0/composer", // leading v stripped
		"phpunit/phpunit@9.6.0/composer",   // dev group included
	)
}

func TestParseSwiftPackageResolvedV2(t *testing.T) {
	body := []byte(`{
		"pins": [
			{"identity": "alamofire", "state": {"version": "5.8.1"}},
			{"identity": "swift-log", "state": {"version": "1.5.3"}},
			{"identity": "branch-pin", "state": {"branch": "main", "revision": "abc"}}
		],
		"version": 2
	}`)
	deps, err := Parse("Package.resolved", body)
	if err != nil {
		t.Fatalf("Parse(Package.resolved v2): %v", err)
	}
	assertContains(t, deps,
		"alamofire@5.8.1/swift",
		"swift-log@1.5.3/swift",
	)
	// A branch/revision pin has no released version -> skipped.
	for _, d := range deps {
		if d.Name == "branch-pin" {
			t.Errorf("branch pin should be skipped, got %+v", d)
		}
	}
}

func TestParseSwiftPackageResolvedV1(t *testing.T) {
	body := []byte(`{
		"object": {
			"pins": [
				{"package": "Alamofire", "state": {"version": "5.8.1"}}
			]
		},
		"version": 1
	}`)
	deps, err := Parse("Package.resolved", body)
	if err != nil {
		t.Fatalf("Parse(Package.resolved v1): %v", err)
	}
	assertContains(t, deps, "Alamofire@5.8.1/swift")
}

func TestParsePubspecLock(t *testing.T) {
	body := []byte(`# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "0.13.5"
  meta:
    dependency: transitive
    source: hosted
    version: "1.8.0"
sdks:
  dart: ">=2.17.0 <3.0.0"
`)
	deps, err := Parse("pubspec.lock", body)
	if err != nil {
		t.Fatalf("Parse(pubspec.lock): %v", err)
	}
	assertContains(t, deps,
		"http@0.13.5/pub",
		"meta@1.8.0/pub",
	)
	// The sdks: section must not leak in as a package.
	for _, d := range deps {
		if d.Name == "dart" {
			t.Errorf("sdks section leaked as a package: %+v", d)
		}
	}
}

func TestNewParsersMalformed(t *testing.T) {
	for _, name := range []string{"composer.lock", "Package.resolved"} {
		if _, err := Parse(name, []byte(`{bad json`)); err == nil {
			t.Errorf("Parse(%s, malformed) should error", name)
		}
	}
	// pubspec.lock is line-oriented and tolerant: garbage yields no rows,
	// not an error.
	if deps, err := Parse("pubspec.lock", []byte("garbage\nno packages here\n")); err != nil || len(deps) != 0 {
		t.Errorf("pubspec.lock garbage: deps=%v err=%v", deps, err)
	}
}

// TestParseRequirementsRangesEmitNames covers the gap where a loosely
// pinned (or bare) pip requirement was dropped entirely: the NAME is now
// emitted (empty version) so the curated malicious/typosquat checks run,
// mirroring the package.json manifest behaviour. URL/option lines must
// not be mistaken for package names.
func TestParseRequirementsRangesEmitNames(t *testing.T) {
	body := []byte(`numpy>=1.24
Pillow>=10.0
requests[security]~=2.0
flask==3.0.0
django < 5
# a comment
-r other-requirements.txt
--hash=sha256:deadbeef
https://example.com/pkg-1.0.whl
barepkg
`)
	deps, err := Parse("requirements.txt", body)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	assertContains(t, deps,
		"numpy@/pypi",      // range -> name, empty version
		"Pillow@/pypi",     // range
		"requests@/pypi",   // extras stripped
		"django@/pypi",     // space before operator
		"flask@3.0.0/pypi", // exact pin keeps version
		"barepkg@/pypi",    // bare name
	)
	for _, d := range deps {
		if d.Name == "https" || d.Name == "r" || d.Name == "" {
			t.Errorf("URL/option line emitted as a package: %+v", d)
		}
	}
}
