package compiler

import (
	"fmt"
	"strings"

	"github.com/kennguy3n/skills-library/internal/skill"
)

type cursorFormatter struct{}

func (cursorFormatter) Name() string            { return "cursor" }
func (cursorFormatter) OutputName() string      { return ".cursorrules" }
func (cursorFormatter) DefaultTier() skill.Tier { return skill.TierCompact }

// Format renders dist/.cursorrules. Since v3 the default output is a
// minimal pointer file (<4 KiB) matching dist/AGENTS.md. The legacy
// monolithic output that inlines every skill body remains available
// via `skills-check regenerate --full-inline` (alias --legacy).
func (cursorFormatter) Format(skills []*skill.Skill, tier skill.Tier, ctx Context) string {
	if ctx.fullInline() {
		return renderCursorFullInline(skills, tier, ctx)
	}
	return RenderPointer(PointerSpec{
		OutputFile:    ".cursorrules",
		Audience:      "this Cursor workspace",
		CommentPrefix: "# ",
	}, skills)
}

func renderCursorFullInline(skills []*skill.Skill, tier skill.Tier, ctx Context) string {
	var b strings.Builder
	b.WriteString("# Skills Library — Cursor security rules\n")
	b.WriteString("# Generated by skills-check; do not edit by hand.\n\n")
	b.WriteString("You are a security-conscious coding assistant. Apply every rule below to\n")
	b.WriteString("every file you touch in this project.\n\n")
	for _, s := range skills {
		fmt.Fprintf(&b, "## %s (%s, %s)\n", s.Frontmatter.Title, s.Frontmatter.Category, s.Frontmatter.Severity)
		for _, line := range s.Body.Always {
			fmt.Fprintf(&b, "- ALWAYS: %s\n", line)
		}
		for _, line := range s.Body.Never {
			fmt.Fprintf(&b, "- NEVER: %s\n", line)
		}
		if tier != skill.TierMinimal {
			for _, line := range s.Body.KnownFalsePositives {
				fmt.Fprintf(&b, "- FALSE POSITIVE: %s\n", line)
			}
		}
		b.WriteString("\n")
	}
	b.WriteString(VulnSummary(ctx))
	b.WriteString(GlossaryBlock(ctx))
	return b.String()
}
