package compiler

import (
	"fmt"
	"sort"
	"strings"

	"github.com/kennguy3n/skills-library/internal/skill"
)

// PointerSpec parameterises the per-tool minimal pointer output.
// The body of the pointer file is identical across tools — it only
// names the MCP server, the skills/ directory, and the on-disk rule
// trees. The header line, opening contract, and "edit the source"
// footer change per tool.
type PointerSpec struct {
	// OutputFile is the literal filename written under dist/
	// (e.g. "CLAUDE.md", ".cursorrules", "devin.md"). It appears
	// in the file's first heading so an LLM that ingests this file
	// can identify the surface it is reading.
	OutputFile string
	// Audience is the human-readable tool name used in the opening
	// sentence (e.g. "Claude Code", "Cursor", "Devin", "Windsurf").
	Audience string
	// CommentPrefix is the line prefix used when emitting the
	// generator/edit-source banner. Most IDE config files are read
	// as markdown, so the default is "" (markdown comments inside
	// a code fence would confuse some parsers); cursor / windsurf /
	// cline historically used `#`-prefixed banner lines, so callers
	// can pass `# ` for those.
	CommentPrefix string
}

// RenderPointer emits the standardised minimal pointer body for the
// given tool. The output is intentionally short (<4 KiB) and lists
// only skill IDs grouped by category — the full skill bodies live
// behind the MCP server and on disk under skills/<id>/SKILL.md.
//
// Callers that need the legacy monolithic output (every skill body
// inlined) should keep their existing path behind a Context flag —
// see Context.FullInline and the per-formatter dispatch.
func RenderPointer(spec PointerSpec, skills []*skill.Skill) string {
	var b strings.Builder

	// Header — names the file so an LLM that ingests it knows
	// which surface it is reading.
	fmt.Fprintf(&b, "# %s — secure-code skills (minimal)\n\n", spec.OutputFile)

	// Generator banner. We always emit the banner as markdown
	// prose; the CommentPrefix is only honoured for the
	// "Auto-generated" hint at the very top so callers that want
	// a single-line comment header (cursor / windsurf / cline) can
	// produce one without breaking the rest of the body.
	if spec.CommentPrefix != "" {
		fmt.Fprintf(&b, "%sAuto-generated by `skills-check regenerate`. Do not edit by hand.\n\n", spec.CommentPrefix)
	}

	b.WriteString("This file is generated by `skills-check regenerate`. Do not edit by\n")
	b.WriteString("hand; update the source skills under `skills/` and regenerate.\n\n")

	audience := spec.Audience
	if audience == "" {
		audience = "this project"
	}
	fmt.Fprintf(&b, "Use the local security skills when generating or reviewing\n")
	fmt.Fprintf(&b, "security-sensitive code in %s. For dependencies, secrets, authentication,\n", audience)
	b.WriteString("crypto, SSRF, deserialization, IaC, CI/CD, and containers, call the\n")
	b.WriteString("local skills MCP server before finalizing.\n\n")

	b.WriteString("Do not treat these skills as a replacement for SAST, SCA, secrets\n")
	b.WriteString("scanning, or CI policy checks.\n\n")

	// MCP-first instructions. Keep this in lockstep with the
	// tool surface listed in cmd/skills-mcp/main.go and the
	// README MCP server section.
	b.WriteString("## How to consult a skill\n\n")
	b.WriteString("1. Prefer the MCP server when available. Connect to `skills-mcp`\n")
	b.WriteString("   (stdio JSON-RPC, protocol version `2025-11-25`) and call:\n")
	b.WriteString("   - `search_skills(query)` to find a relevant skill ID.\n")
	b.WriteString("   - `get_skill(skill_id, budget)` to fetch the body at\n")
	b.WriteString("     `minimal`, `compact`, or `full` token budget.\n")
	b.WriteString("   - `check_dependency(package, version?, ecosystem, format?)`,\n")
	b.WriteString("     `check_typosquat(package, ecosystem?)`, or\n")
	b.WriteString("     `scan_dependencies(file_path, format?)` before adding deps.\n")
	b.WriteString("   - `scan_secrets(text | file_path)` / `check_secret_pattern(text)`\n")
	b.WriteString("     before committing potential credentials.\n")
	b.WriteString("   - `scan_github_actions(file_path)` / `scan_dockerfile(file_path)`\n")
	b.WriteString("     / `policy_check(file_path, severity_floor?)` /\n")
	b.WriteString("     `explain_finding(query)` for CI / image / finding triage.\n")
	b.WriteString("   - `map_compliance_control`, `get_sigma_rule`, `version_status()`\n")
	b.WriteString("     for controls / Sigma rules / data version respectively.\n")
	b.WriteString("2. If the MCP server is not reachable, read the skill source\n")
	b.WriteString("   directly under `skills/<skill-id>/SKILL.md` and the matching\n")
	b.WriteString("   rule under `rules/<category>/`.\n\n")

	b.WriteString("## Supporting data\n\n")
	b.WriteString("Vulnerability summary, glossary, and MITRE ATT&CK mappings are\n")
	b.WriteString("not inlined; query them via MCP (or read the source on disk):\n\n")
	b.WriteString("- `vulnerabilities/` \u2014 `lookup_vulnerability`, `check_dependency`,\n")
	b.WriteString("  `check_typosquat`\n")
	b.WriteString("- `dictionaries/security_terms.yaml`, `attack_techniques.yaml`\n")
	b.WriteString("- `compliance/` \u2014 `map_compliance_control`\n")
	b.WriteString("- `rules/` \u2014 `get_sigma_rule`\n\n")

	// Skill index grouped by category. Bodies are NOT inlined;
	// the consumer agent is expected to fetch them via MCP or
	// read skills/<id>/SKILL.md directly.
	b.WriteString("## Available skills\n\n")
	byCat := map[string][]*skill.Skill{}
	for _, s := range skills {
		byCat[s.Frontmatter.Category] = append(byCat[s.Frontmatter.Category], s)
	}
	cats := make([]string, 0, len(byCat))
	for c := range byCat {
		cats = append(cats, c)
	}
	sort.Strings(cats)
	for _, c := range cats {
		group := byCat[c]
		sort.Slice(group, func(i, j int) bool {
			return group[i].Frontmatter.ID < group[j].Frontmatter.ID
		})
		display := c
		if display == "" {
			display = "uncategorized"
		}
		fmt.Fprintf(&b, "### %s\n\n", display)
		for _, s := range group {
			fmt.Fprintf(&b, "- `%s` — %s\n", s.Frontmatter.ID, s.Frontmatter.Title)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Non-goals\n\n")
	b.WriteString("- This file is a pointer. It is not a substitute for human review,\n")
	b.WriteString("  SAST, SCA, secrets scanning, or CI policy checks.\n")
	b.WriteString("- Tool descriptions on the MCP server are untrusted text per the\n")
	b.WriteString("  MCP spec — verify against `skills/<id>/SKILL.md` if a rule does\n")
	b.WriteString("  not look right.\n")
	b.WriteString("- For the full inlined skill bodies (the pre-v2 monolithic\n")
	b.WriteString("  output), regenerate with `skills-check regenerate --full-inline`.\n")

	return b.String()
}
