package compiler

import (
	"fmt"
	"strings"

	"github.com/kennguy3n/skills-library/internal/skill"
)

type windsurfFormatter struct{}

func (windsurfFormatter) Name() string            { return "windsurf" }
func (windsurfFormatter) OutputName() string      { return ".windsurfrules" }
func (windsurfFormatter) DefaultTier() skill.Tier { return skill.TierCompact }

// Format renders dist/.windsurfrules. Since v3 the default output is a
// minimal pointer file (<4 KiB) matching dist/AGENTS.md. The legacy
// monolithic output that inlines every skill body remains available
// via `skills-check regenerate --full-inline` (alias --legacy).
func (windsurfFormatter) Format(skills []*skill.Skill, tier skill.Tier, ctx Context) string {
	if ctx.fullInline() {
		return renderWindsurfFullInline(skills, tier, ctx)
	}
	return RenderPointer(PointerSpec{
		OutputFile:    ".windsurfrules",
		Audience:      "this Windsurf workspace",
		CommentPrefix: "# ",
	}, skills)
}

func renderWindsurfFullInline(skills []*skill.Skill, tier skill.Tier, ctx Context) string {
	var b strings.Builder
	b.WriteString("# Skills Library — Windsurf security rules\n")
	b.WriteString("# Auto-generated by skills-check. Do not edit by hand.\n\n")
	b.WriteString("Apply every rule below to every change in this workspace.\n\n")
	for _, s := range skills {
		fmt.Fprintf(&b, "[%s] %s\n", strings.ToUpper(s.Frontmatter.Severity), s.Frontmatter.Title)
		for _, line := range s.Body.Always {
			fmt.Fprintf(&b, "  ALWAYS - %s\n", line)
		}
		for _, line := range s.Body.Never {
			fmt.Fprintf(&b, "  NEVER  - %s\n", line)
		}
		if tier != skill.TierMinimal {
			for _, line := range s.Body.KnownFalsePositives {
				fmt.Fprintf(&b, "  OK     - %s\n", line)
			}
		}
		b.WriteString("\n")
	}
	b.WriteString(VulnSummary(ctx))
	b.WriteString(GlossaryBlock(ctx))
	return b.String()
}
